//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinderGarten.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Musatova_KinderGratenEntities : DbContext
    {
        public Musatova_KinderGratenEntities()
            : base("name=Musatova_KinderGratenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activity { get; set; }
        public DbSet<Direction> Direction { get; set; }
        public DbSet<GroupDS> GroupDS { get; set; }
        public DbSet<Journal> Journal { get; set; }
        public DbSet<Mark> Mark { get; set; }
        public DbSet<VidGroup> VidGroup { get; set; }
    }
}
