//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinderGarten.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidGroup
    {
        public VidGroup()
        {
            this.GroupDS = new HashSet<GroupDS>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GroupDS> GroupDS { get; set; }
    }
}
